class Data:
    def __init__(self):
        self.init_data()
        # l_agents -> [(zh, en), (zh, en), ...]
        self.l_agent = [(zh, self.d_agent[zh]["en"]) for zh in self.d_agent]
        # l_tags -> ["支援", "辅助干员", ...]
        self.l_tag = []
        for num in self.d_tag:
            self.l_tag += self.d_tag[num]

    def is_special(self, tag):
        if tag in self.d_tag[4]:
            return True
        return False

    def getTagPriority(self, tag):
        for num in self.d_tag:
            if tag in self.d_tag[num]:
                return num
        raise ValueError(f"{tag}不是合法的值")

    def init_data(self):
        self.d_tag = {
            0: [
                '支援机械',
            ],
            1: [
                '先锋干员',
                '近卫干员',
                '狙击干员',
                '重装干员',
                '医疗干员',
                '辅助干员',
                '术士干员',
                '近战位',
                '远程位',
                '新手',
            ],
            2: [
                '治疗',
                '输出',
                '群攻',
                '减速',
                '生存',
                '防护',
                '费用回复'
            ],
            3: [
                '特种干员',
                '支援',
                '削弱',
                '位移',
                '快速复活',
                '爆发',
                '控场',
            ],
            4: [
                '元素',
                '召唤',
                '资深干员',
                '高级资深干员',
            ],
        }

        self.d_agent = {
'W':{'en': 'W', 'star': '5', 'tag': ['狙击干员', '远程位', '输出', '控场'], 'subprofession': '炮手'},
'万顷':{'en': 'Wanqing', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '支援'], 'subprofession': '执旗手'},
'临光':{'en': 'Nearl', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '治疗'], 'subprofession': '守护者'},
'乌尔比安':{'en': 'Ulpianus', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '重剑手'},
'乌有':{'en': 'Mr.Nothing', 'star': '4', 'tag': ['特种干员', '近战位', '快速复活', '输出'], 'subprofession': '行商'},
'九色鹿':{'en': 'Nine-Colored Deer', 'star': '4', 'tag': ['辅助干员', '远程位', '支援', '生存'], 'subprofession': '护佑者'},
'云迹':{'en': 'Contrail', 'star': '3', 'tag': ['特种干员', '近战位', '高空', '控场'], 'subprofession': '巡空者'},
'亚叶':{'en': 'Folinic', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗', '输出'], 'subprofession': '医师'},
'仇白':{'en': 'Qiubai', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '控场'], 'subprofession': '领主'},
'令':{'en': 'Ling', 'star': '5', 'tag': ['辅助干员', '远程位', '召唤', '支援', '控场'], 'subprofession': '召唤师'},
'伊内丝':{'en': 'Ines', 'star': '5', 'tag': ['先锋干员', '近战位', '费用回复', '快速复活'], 'subprofession': '情报官'},
'伊桑':{'en': 'Ethan', 'star': '3', 'tag': ['特种干员', '近战位', '输出', '控场'], 'subprofession': '伏击客'},
'伊芙利特':{'en': 'Ifrit', 'star': '5', 'tag': ['术师干员', '远程位', '群攻', '削弱'], 'subprofession': '轰击术师'},
'休谟斯':{'en': 'Humus', 'star': '3', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '收割者'},
'伺夜':{'en': 'Vigil', 'star': '5', 'tag': ['先锋干员', '远程位', '费用回复', '控场'], 'subprofession': '战术家'},
'但书':{'en': 'Proviso', 'star': '4', 'tag': ['辅助干员', '远程位', '削弱', '减速'], 'subprofession': '凝滞师'},
'佩佩':{'en': 'Pepe', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '控场'], 'subprofession': '撼地者'},
'假日威龙陈':{'en': "Ch'en the Holungday", 'star': '5', 'tag': ['狙击干员', '远程位', '输出', '群攻'], 'subprofession': '散射手'},
'傀影':{'en': 'Phantom', 'star': '5', 'tag': ['特种干员', '近战位', '快速复活', '控场', '输出'], 'subprofession': '处决者'},
'克洛丝':{'en': 'Kroos', 'star': '2', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'冰酿':{'en': 'Coldshot', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '猎手'},
'凛冬':{'en': 'Зима', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '支援'], 'subprofession': '尖兵'},
'凛视':{'en': 'Valarqvin', 'star': '4', 'tag': ['辅助干员', '远程位', '元素'], 'subprofession': '巫役'},
'凯尔希':{'en': "Kal'tsit", 'star': '5', 'tag': ['医疗干员', '远程位', '召唤', '治疗'], 'subprofession': '医师'},
'凯瑟琳':{'en': 'Catherine', 'star': '4', 'tag': ['辅助干员', '近战位', '防护', '支援'], 'subprofession': '工匠'},
'初雪':{'en': 'Pramanix', 'star': '4', 'tag': ['辅助干员', '远程位', '削弱'], 'subprofession': '削弱者'},
'刺玫':{'en': 'Vendela', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '咒愈师'},
'刻俄柏':{'en': 'Ceobe', 'star': '5', 'tag': ['术师干员', '远程位', '输出', '控场'], 'subprofession': '中坚术师'},
'刻刀':{'en': 'Cutter', 'star': '3', 'tag': ['近卫干员', '近战位', '爆发', '输出'], 'subprofession': '剑豪'},
'医生':{'en': 'Doc', 'star': '4', 'tag': ['近卫干员', '近战位', '治疗', '支援'], 'subprofession': '教官'},
'华法琳':{'en': 'Warfarin', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗', '支援'], 'subprofession': '医师'},
'卡夫卡':{'en': 'Kafka', 'star': '4', 'tag': ['特种干员', '近战位', '快速复活', '控场'], 'subprofession': '处决者'},
'卡涅利安':{'en': 'Carnelian', 'star': '5', 'tag': ['术师干员', '远程位', '群攻', '防护'], 'subprofession': '阵法术师'},
'卡缇':{'en': 'Cardigan', 'star': '2', 'tag': ['重装干员', '近战位', '防护'], 'subprofession': '铁卫'},
'卡达':{'en': 'Click', 'star': '3', 'tag': ['术师干员', '远程位', '输出', '控场'], 'subprofession': '驭械术师'},
'历阵锐枪芬':{'en': 'Fang the Fire-sharpened', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '冲锋手'},
'双月':{'en': 'Iana', 'star': '4', 'tag': ['特种干员', '近战位', '削弱', '快速复活'], 'subprofession': '傀儡师'},
'古米':{'en': 'Гум', 'star': '3', 'tag': ['重装干员', '近战位', '防护', '治疗'], 'subprofession': '守护者'},
'可颂':{'en': 'Croissant', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '位移'], 'subprofession': '铁卫'},
'史尔特尔':{'en': 'Surtr', 'star': '5', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '术战者'},
'史都华德':{'en': 'Steward', 'star': '2', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '中坚术师'},
'号角':{'en': 'Horn', 'star': '5', 'tag': ['重装干员', '近战位', '输出', '防护'], 'subprofession': '要塞'},
'吽':{'en': 'Hung', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '治疗'], 'subprofession': '守护者'},
'和弦':{'en': 'Harmonie', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '秘术师'},
'哈洛德':{'en': 'Harold', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '行医'},
'嘉维尔':{'en': 'Gavial', 'star': '3', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '医师'},
'四月':{'en': 'April', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'因陀罗':{'en': 'Indra', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '斗士'},
'图耶':{'en': 'Tuye', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '医师'},
'圣约送葬人':{'en': 'Executor the Ex Foedere', 'star': '5', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '收割者'},
'地灵':{'en': 'Earthspirit', 'star': '3', 'tag': ['辅助干员', '远程位', '减速'], 'subprofession': '凝滞师'},
'坚雷':{'en': 'Dur-nar', 'star': '3', 'tag': ['重装干员', '近战位', '防护', '输出'], 'subprofession': '驭法铁卫'},
'埃拉托':{'en': 'Erato', 'star': '4', 'tag': ['狙击干员', '远程位', '输出', '控场'], 'subprofession': '攻城手'},
'塑心':{'en': 'Virtuosa', 'star': '5', 'tag': ['辅助干员', '远程位', '元素', '支援'], 'subprofession': '巫役'},
'塞雷娅':{'en': 'Saria', 'star': '5', 'tag': ['重装干员', '近战位', '防护', '治疗', '支援'], 'subprofession': '守护者'},
'夏栎':{'en': 'Quercus', 'star': '4', 'tag': ['辅助干员', '远程位', '支援', '生存'], 'subprofession': '护佑者'},
'夕':{'en': 'Dusk', 'star': '5', 'tag': ['术师干员', '远程位', '群攻', '输出', '控场'], 'subprofession': '扩散术师'},
'多萝西':{'en': 'Dorothy', 'star': '5', 'tag': ['特种干员', '远程位', '召唤', '控场'], 'subprofession': '陷阱师'},
'夜刀':{'en': 'Yato', 'star': '1', 'tag': ['先锋干员', '近战位', '新手'], 'subprofession': '尖兵'},
'夜半':{'en': 'Blacknight', 'star': '4', 'tag': ['先锋干员', '远程位', '费用回复', '控场'], 'subprofession': '战术家'},
'夜烟':{'en': 'Haze', 'star': '3', 'tag': ['术师干员', '远程位', '输出', '削弱'], 'subprofession': '中坚术师'},
'夜莺':{'en': 'Nightingale', 'star': '5', 'tag': ['医疗干员', '远程位', '治疗', '支援'], 'subprofession': '群愈师'},
'夜魔':{'en': 'Nightmare', 'star': '4', 'tag': ['术师干员', '远程位', '输出', '治疗', '减速'], 'subprofession': '中坚术师'},
'天火':{'en': 'Skyfire', 'star': '4', 'tag': ['术师干员', '远程位', '群攻', '控场'], 'subprofession': '扩散术师'},
'奥斯塔':{'en': 'Aosta', 'star': '4', 'tag': ['狙击干员', '远程位', '群攻'], 'subprofession': '散射手'},
'奥达':{'en': 'Odda', 'star': '4', 'tag': ['近卫干员', '近战位', '群攻', '控场'], 'subprofession': '撼地者'},
'妮芙':{'en': 'Nymph', 'star': '5', 'tag': ['术师干员', '远程位', '元素', '输出', '控场'], 'subprofession': '本源术师'},
'娜仁图亚':{'en': 'Narantuya', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '回环射手'},
'子月':{'en': 'Lunacub', 'star': '4', 'tag': ['狙击干员', '远程位', '输出', '生存'], 'subprofession': '神射手'},
'孑':{'en': 'Jaye', 'star': '3', 'tag': ['特种干员', '近战位', '快速复活', '输出'], 'subprofession': '行商'},
'守林人':{'en': 'Firewatch', 'star': '4', 'tag': ['狙击干员', '远程位', '输出', '爆发'], 'subprofession': '神射手'},
'安哲拉':{'en': 'Andreana', 'star': '4', 'tag': ['狙击干员', '远程位', '输出', '减速'], 'subprofession': '神射手'},
'安德切尔':{'en': 'Adnachiel', 'star': '2', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'安比尔':{'en': 'Ambriel', 'star': '3', 'tag': ['狙击干员', '远程位', '输出', '减速'], 'subprofession': '神射手'},
'安洁莉娜':{'en': 'Angelina', 'star': '5', 'tag': ['辅助干员', '远程位', '减速', '输出', '支援'], 'subprofession': '凝滞师'},
'安赛尔':{'en': 'Ansel', 'star': '2', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '医师'},
'宴':{'en': 'Utage', 'star': '3', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '武者'},
'寒檀':{'en': 'Santalla', 'star': '4', 'tag': ['术师干员', '远程位', '群攻', '控场'], 'subprofession': '扩散术师'},
'寒芒克洛丝':{'en': 'Kroos the Keen Glint', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'导火索':{'en': 'Fuze', 'star': '4', 'tag': ['近卫干员', '近战位', '群攻', '生存'], 'subprofession': '强攻手'},
'小满':{'en': 'Grain Buds', 'star': '4', 'tag': ['辅助干员', '远程位', '减速', '控场'], 'subprofession': '凝滞师'},
'山':{'en': 'Mountain', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '斗士'},
'崖心':{'en': 'Cliffheart', 'star': '4', 'tag': ['特种干员', '近战位', '位移', '输出'], 'subprofession': '钩索师'},
'嵯峨':{'en': 'Saga', 'star': '5', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '尖兵'},
'巡林者':{'en': 'Rangers', 'star': '1', 'tag': ['狙击干员', '远程位', '新手'], 'subprofession': '速射手'},
'左乐':{'en': 'Zuo Le', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '武者'},
'巫恋':{'en': 'Shamare', 'star': '4', 'tag': ['辅助干员', '远程位', '削弱'], 'subprofession': '削弱者'},
'布丁':{'en': 'Pudding', 'star': '3', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '链术师'},
'布洛卡':{'en': 'Broca', 'star': '4', 'tag': ['近卫干员', '近战位', '群攻', '生存'], 'subprofession': '强攻手'},
'帕拉斯':{'en': 'Pallas', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '支援'], 'subprofession': '教官'},
'年':{'en': 'Nian', 'star': '5', 'tag': ['重装干员', '近战位', '防护', '支援'], 'subprofession': '铁卫'},
'幽灵鲨':{'en': 'Specter', 'star': '4', 'tag': ['近卫干员', '近战位', '群攻', '生存'], 'subprofession': '强攻手'},
'异客':{'en': 'Passenger', 'star': '5', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '链术师'},
'弑君者':{'en': 'Crownslayer', 'star': '5', 'tag': ['特种干员', '近战位', '快速复活'], 'subprofession': '处决者'},
'引星棘刺':{'en': 'Thorns the Lodestar', 'star': '5', 'tag': ['特种干员', '远程位', '输出', '支援', '削弱'], 'subprofession': '炼金师'},
'归溟幽灵鲨':{'en': 'Specter the Unchained', 'star': '5', 'tag': ['特种干员', '近战位', '输出', '快速复活'], 'subprofession': '傀儡师'},
'微风':{'en': 'Breeze', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗', '支援'], 'subprofession': '群愈师'},
'德克萨斯':{'en': 'Texas', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '控场'], 'subprofession': '尖兵'},
'忍冬':{'en': 'Vulpisfoglia', 'star': '5', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '尖兵'},
'惊蛰':{'en': 'Leizi', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '链术师'},
'慑砂':{'en': 'Sesa', 'star': '4', 'tag': ['狙击干员', '远程位', '群攻', '削弱'], 'subprofession': '炮手'},
'慕斯':{'en': 'Mousse', 'star': '3', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '术战者'},
'战车':{'en': 'Tachanka', 'star': '4', 'tag': ['近卫干员', '近战位', '爆发', '输出'], 'subprofession': '剑豪'},
'截云':{'en': 'Jieyun', 'star': '4', 'tag': ['狙击干员', '远程位', '群攻', '减速'], 'subprofession': '炮手'},
'戴菲恩':{'en': 'Delphine', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '秘术师'},
'承曦格雷伊':{'en': 'Greyy the Lightningbearer', 'star': '4', 'tag': ['狙击干员', '远程位', '输出', '减速'], 'subprofession': '投掷手'},
'折光':{'en': 'Diamante', 'star': '4', 'tag': ['术师干员', '远程位', '元素', '输出'], 'subprofession': '本源术师'},
'拉普兰德':{'en': 'Lappland', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '削弱'], 'subprofession': '领主'},
'拜松':{'en': 'Bison', 'star': '4', 'tag': ['重装干员', '近战位', '防护'], 'subprofession': '铁卫'},
'掠风':{'en': 'Windflit', 'star': '4', 'tag': ['辅助干员', '近战位', '输出', '支援'], 'subprofession': '工匠'},
'推进之王':{'en': 'Siege', 'star': '5', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '尖兵'},
'提丰':{'en': 'Typhon', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '攻城手'},
'摩根':{'en': 'Morgan', 'star': '4', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '无畏者'},
'斑点':{'en': 'Spot', 'star': '2', 'tag': ['重装干员', '近战位', '防护', '治疗'], 'subprofession': '守护者'},
'斥罪':{'en': 'Penance', 'star': '5', 'tag': ['重装干员', '近战位', '生存', '输出'], 'subprofession': '不屈者'},
'断崖':{'en': 'Ayerscarpe', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '群攻'], 'subprofession': '领主'},
'断罪者':{'en': 'Conviction', 'star': '3', 'tag': ['近卫干员', '近战位', '输出', '生存', '控场', '爆发'], 'subprofession': '无畏者'},
'斯卡蒂':{'en': 'Skadi', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '无畏者'},
'早露':{'en': 'Роса', 'star': '5', 'tag': ['狙击干员', '远程位', '输出', '控场'], 'subprofession': '攻城手'},
'明椒':{'en': 'Paprika', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '链愈师'},
'星极':{'en': 'Astesia', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '防护'], 'subprofession': '术战者'},
'星源':{'en': 'Astgenne', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '链术师'},
'星熊':{'en': 'Hoshiguma', 'star': '5', 'tag': ['重装干员', '近战位', '防护', '输出'], 'subprofession': '铁卫'},
'晓歌':{'en': 'Cantabile', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '快速复活'], 'subprofession': '情报官'},
'普罗旺斯':{'en': 'Provence', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '重射手'},
'暗索':{'en': 'Rope', 'star': '3', 'tag': ['特种干员', '近战位', '位移'], 'subprofession': '钩索师'},
'暮落':{'en': 'Shalem', 'star': '4', 'tag': ['重装干员', '近战位', '输出', '防护'], 'subprofession': '驭法铁卫'},
'暴行':{'en': 'Savage', 'star': '4', 'tag': ['近卫干员', '近战位', '群攻', '爆发'], 'subprofession': '强攻手'},
'暴雨':{'en': 'Heavyrain', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '支援'], 'subprofession': '铁卫'},
'月禾':{'en': 'Tsukinogi', 'star': '4', 'tag': ['辅助干员', '远程位', '支援', '生存'], 'subprofession': '护佑者'},
'月见夜':{'en': 'Midnight', 'star': '2', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '领主'},
'末药':{'en': 'Myrrh', 'star': '3', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '医师'},
'杏仁':{'en': 'Almond', 'star': '4', 'tag': ['特种干员', '近战位', '位移'], 'subprofession': '钩索师'},
'杜宾':{'en': 'Dobermann', 'star': '3', 'tag': ['近卫干员', '近战位', '输出', '支援'], 'subprofession': '教官'},
'杜林':{'en': 'Durin', 'star': '1', 'tag': ['术师干员', '远程位', '新手'], 'subprofession': '中坚术师'},
'杰克':{'en': 'Jackie', 'star': '3', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '斗士'},
'杰西卡':{'en': 'Jessica', 'star': '3', 'tag': ['狙击干员', '远程位', '输出', '生存'], 'subprofession': '速射手'},
'松果':{'en': 'Pinecone', 'star': '3', 'tag': ['狙击干员', '远程位', '群攻', '输出'], 'subprofession': '散射手'},
'极光':{'en': 'Aurora', 'star': '4', 'tag': ['重装干员', '近战位', '输出', '防护'], 'subprofession': '决战者'},
'极境':{'en': 'Elysium', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '支援'], 'subprofession': '执旗手'},
'林':{'en': 'Lin', 'star': '5', 'tag': ['术师干员', '远程位', '群攻', '防护'], 'subprofession': '阵法术师'},
'柏喙':{'en': 'Bibeak', 'star': '4', 'tag': ['近卫干员', '近战位', '爆发', '输出'], 'subprofession': '剑豪'},
'格劳克斯':{'en': 'Glaucus', 'star': '4', 'tag': ['辅助干员', '远程位', '减速', '控场'], 'subprofession': '凝滞师'},
'格拉尼':{'en': 'Grani', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '防护'], 'subprofession': '冲锋手'},
'格雷伊':{'en': 'Greyy', 'star': '3', 'tag': ['术师干员', '远程位', '群攻', '减速'], 'subprofession': '扩散术师'},
'桃金娘':{'en': 'Myrtle', 'star': '3', 'tag': ['先锋干员', '近战位', '费用回复', '治疗'], 'subprofession': '执旗手'},
'桑葚':{'en': 'Mulberry', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '行医'},
'梅':{'en': 'May', 'star': '3', 'tag': ['狙击干员', '远程位', '输出', '减速'], 'subprofession': '速射手'},
'梅尔':{'en': 'Mayer', 'star': '4', 'tag': ['辅助干员', '远程位', '召唤', '控场'], 'subprofession': '召唤师'},
'梓兰':{'en': 'Orchid', 'star': '2', 'tag': ['辅助干员', '远程位', '减速'], 'subprofession': '凝滞师'},
'棘刺':{'en': 'Thorns', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '防护'], 'subprofession': '领主'},
'森蚺':{'en': 'Eunectes', 'star': '5', 'tag': ['重装干员', '近战位', '输出', '生存', '防护'], 'subprofession': '决战者'},
'森西':{'en': 'Senshi', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '治疗'], 'subprofession': '守护者'},
'槐琥':{'en': 'Waai Fu', 'star': '4', 'tag': ['特种干员', '近战位', '快速复活', '削弱'], 'subprofession': '处决者'},
'歌蕾蒂娅':{'en': 'Gladiia', 'star': '5', 'tag': ['特种干员', '近战位', '位移', '输出', '控场'], 'subprofession': '钩索师'},
'止颂':{'en': 'Lessing', 'star': '5', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '无畏者'},
'正义骑士号':{'en': '"Justice Knight"', 'star': '0', 'tag': ['狙击干员', '远程位', '支援机械', '支援'], 'subprofession': '速射手'},
'水月':{'en': 'Mizuki', 'star': '5', 'tag': ['特种干员', '近战位', '输出', '控场'], 'subprofession': '伏击客'},
'泡普卡':{'en': 'Popukar', 'star': '2', 'tag': ['近卫干员', '近战位', '群攻', '生存'], 'subprofession': '强攻手'},
'泡泡':{'en': 'Bubble', 'star': '3', 'tag': ['重装干员', '近战位', '防护'], 'subprofession': '铁卫'},
'波卜':{'en': 'Bobbing', 'star': '4', 'tag': ['辅助干员', '远程位', '元素'], 'subprofession': '巫役'},
'波登可':{'en': 'Podenco', 'star': '3', 'tag': ['辅助干员', '远程位', '减速', '治疗'], 'subprofession': '凝滞师'},
'泥岩':{'en': 'Mudrock', 'star': '5', 'tag': ['重装干员', '近战位', '生存', '防护', '输出'], 'subprofession': '不屈者'},
'泰拉大陆调查团':{'en': 'Terra Research Commission', 'star': '0', 'tag': ['狙击干员', '远程位', '控场'], 'subprofession': '投掷手'},
'洋灰':{'en': 'Cement', 'star': '4', 'tag': ['重装干员', '近战位', '防护'], 'subprofession': '决战者'},
'洛洛':{'en': 'Rockrock', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '驭械术师'},
'流明':{'en': 'Lumen', 'star': '5', 'tag': ['医疗干员', '远程位', '治疗', '支援'], 'subprofession': '疗养师'},
'流星':{'en': 'Meteor', 'star': '3', 'tag': ['狙击干员', '远程位', '输出', '削弱'], 'subprofession': '速射手'},
'浊心斯卡蒂':{'en': 'Skadi the Corrupting Heart', 'star': '5', 'tag': ['辅助干员', '远程位', '支援', '生存', '输出'], 'subprofession': '吟游者'},
'海沫':{'en': 'Highmore', 'star': '4', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '收割者'},
'海蒂':{'en': 'Heidi', 'star': '4', 'tag': ['辅助干员', '远程位', '支援', '治疗'], 'subprofession': '吟游者'},
'海霓':{'en': 'Lucilla', 'star': '4', 'tag': ['辅助干员', '远程位', '削弱'], 'subprofession': '削弱者'},
'涤火杰西卡':{'en': 'Jessica the Liberated', 'star': '5', 'tag': ['重装干员', '近战位', '防护', '生存', '输出'], 'subprofession': '哨戒铁卫'},
'淬羽赫默':{'en': 'Silence the Paradigmatic', 'star': '5', 'tag': ['辅助干员', '远程位', '支援', '生存', '治疗'], 'subprofession': '护佑者'},
'深巡':{'en': 'Underflow', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '输出', '减速'], 'subprofession': '哨戒铁卫'},
'深律':{'en': 'Bassline', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '治疗'], 'subprofession': '守护者'},
'深海色':{'en': 'Deepcolor', 'star': '3', 'tag': ['辅助干员', '远程位', '召唤'], 'subprofession': '召唤师'},
'深靛':{'en': 'Indigo', 'star': '3', 'tag': ['术师干员', '远程位', '输出', '控场'], 'subprofession': '秘术师'},
'清流':{'en': 'Purestream', 'star': '3', 'tag': ['医疗干员', '远程位', '治疗', '支援'], 'subprofession': '疗养师'},
'清道夫':{'en': 'Scavenger', 'star': '3', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '尖兵'},
'渡桥':{'en': 'Mitm', 'star': '4', 'tag': ['先锋干员', '远程位', '费用回复', '爆发'], 'subprofession': '战术家'},
'温米':{'en': 'Warmy', 'star': '4', 'tag': ['术师干员', '远程位', '元素', '爆发'], 'subprofession': '本源术师'},
'温蒂':{'en': 'Weedy', 'star': '5', 'tag': ['特种干员', '近战位', '位移', '输出', '控场'], 'subprofession': '推击手'},
'澄闪':{'en': 'Goldenglow', 'star': '5', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '驭械术师'},
'濯尘芙蓉':{'en': 'Hibiscus the Purifier', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '咒愈师'},
'火哨':{'en': 'Firewhistle', 'star': '4', 'tag': ['重装干员', '近战位', '输出', '防护'], 'subprofession': '要塞'},
'火神':{'en': 'Vulcan', 'star': '4', 'tag': ['重装干员', '近战位', '生存', '防护', '输出'], 'subprofession': '不屈者'},
'火龙S黑角':{'en': 'Rathalos S Noir Corne', 'star': '4', 'tag': ['近卫干员', '近战位', '生存', '输出'], 'subprofession': '武者'},
'灰喉':{'en': 'GreyThroat', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'灰毫':{'en': 'Ashlock', 'star': '4', 'tag': ['重装干员', '近战位', '输出', '防护'], 'subprofession': '要塞'},
'灰烬':{'en': 'Ash', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'灵知':{'en': 'Gnosis', 'star': '5', 'tag': ['辅助干员', '远程位', '削弱'], 'subprofession': '削弱者'},
'炎客':{'en': 'Flamebringer', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '无畏者'},
'炎熔':{'en': 'Lava', 'star': '2', 'tag': ['术师干员', '远程位', '群攻'], 'subprofession': '扩散术师'},
'炎狱炎熔':{'en': 'Lava the Purgatory', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '扩散术师'},
'烈夏':{'en': 'Лето', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '支援'], 'subprofession': '领主'},
'焰尾':{'en': 'Flametail', 'star': '5', 'tag': ['先锋干员', '近战位', '费用回复', '生存'], 'subprofession': '尖兵'},
'焰影苇草':{'en': 'Reed The Flame Shadow', 'star': '5', 'tag': ['医疗干员', '远程位', '治疗', '输出', '削弱'], 'subprofession': '咒愈师'},
'煌':{'en': 'Blaze', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '强攻手'},
'熔泉':{'en': 'Toddifons', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '攻城手'},
'燧石':{'en': 'Flint', 'star': '4', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '斗士'},
'爱丽丝':{'en': 'Iris', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '秘术师'},
'特克诺':{'en': 'Tecno', 'star': '4', 'tag': ['术师干员', '远程位', '召唤'], 'subprofession': '塑灵术师'},
'特米米':{'en': 'Tomimi', 'star': '4', 'tag': ['术师干员', '远程位', '输出', '生存'], 'subprofession': '中坚术师'},
'狮蝎':{'en': 'Manticore', 'star': '4', 'tag': ['特种干员', '近战位', '输出', '生存'], 'subprofession': '伏击客'},
'猎蜂':{'en': 'Beehunter', 'star': '3', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '斗士'},
'玛恩纳':{'en': 'Młynar', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '爆发'], 'subprofession': '解放者'},
'玛露西尔':{'en': 'Marcille', 'star': '5', 'tag': ['术师干员', '远程位', '群攻', '治疗', '控场'], 'subprofession': '扩散术师'},
'玫兰莎':{'en': 'Melantha', 'star': '2', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '无畏者'},
'玫拉':{'en': 'Melanite', 'star': '4', 'tag': ['狙击干员', '远程位', '输出', '爆发'], 'subprofession': '重射手'},
'琳琅诗怀雅':{'en': 'Swire the Elegant Wit', 'star': '5', 'tag': ['特种干员', '近战位', '快速复活', '爆发'], 'subprofession': '行商'},
'琴柳':{'en': 'Saileach', 'star': '5', 'tag': ['先锋干员', '近战位', '费用回复', '支援'], 'subprofession': '执旗手'},
'瑕光':{'en': 'Blemishine', 'star': '5', 'tag': ['重装干员', '近战位', '防护', '治疗', '输出'], 'subprofession': '守护者'},
'瑰盐':{'en': 'Rose Salt', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗', '支援'], 'subprofession': '群愈师'},
'白金':{'en': 'Platinum', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'白铁':{'en': 'Stainless', 'star': '5', 'tag': ['辅助干员', '近战位', '支援', '输出'], 'subprofession': '工匠'},
'白雪':{'en': 'ShiraYuki', 'star': '3', 'tag': ['狙击干员', '远程位', '群攻', '减速'], 'subprofession': '炮手'},
'白面鸮':{'en': 'Ptilopsis', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗', '支援'], 'subprofession': '群愈师'},
'百炼嘉维尔':{'en': 'Gavial the Invincible', 'star': '5', 'tag': ['近卫干员', '近战位', '爆发', '输出', '生存'], 'subprofession': '强攻手'},
'真理':{'en': 'Истина', 'star': '4', 'tag': ['辅助干员', '远程位', '减速', '输出'], 'subprofession': '凝滞师'},
'石棉':{'en': 'Asbestos', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '输出'], 'subprofession': '驭法铁卫'},
'石英':{'en': 'Quartz', 'star': '3', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '重剑手'},
'砾':{'en': 'Gravel', 'star': '3', 'tag': ['特种干员', '近战位', '快速复活', '防护'], 'subprofession': '处决者'},
'稀音':{'en': 'Scene', 'star': '4', 'tag': ['辅助干员', '远程位', '召唤', '支援'], 'subprofession': '召唤师'},
'空':{'en': 'Sora', 'star': '4', 'tag': ['辅助干员', '远程位', '支援', '治疗'], 'subprofession': '吟游者'},
'空弦':{'en': 'Archetto', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'空构':{'en': 'Spuria', 'star': '4', 'tag': ['特种干员', '远程位', '支援', '输出'], 'subprofession': '怪杰'},
'空爆':{'en': 'Catapult', 'star': '2', 'tag': ['狙击干员', '远程位', '群攻'], 'subprofession': '炮手'},
'米格鲁':{'en': 'Beagle', 'star': '2', 'tag': ['重装干员', '近战位', '防护'], 'subprofession': '铁卫'},
'絮雨':{'en': 'Whisperain', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '疗养师'},
'红':{'en': 'Projekt Red', 'star': '4', 'tag': ['特种干员', '近战位', '快速复活', '控场'], 'subprofession': '处决者'},
'红云':{'en': 'Vermeil', 'star': '3', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'红豆':{'en': 'Vigna', 'star': '3', 'tag': ['先锋干员', '近战位', '输出', '费用回复'], 'subprofession': '冲锋手'},
'红隼':{'en': 'Kestrel', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '尖兵'},
'纯烬艾雅法拉':{'en': 'Eyjafjalla the Hvít Aska', 'star': '5', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '行医'},
'绮良':{'en': 'Kirara', 'star': '4', 'tag': ['特种干员', '近战位', '输出', '生存'], 'subprofession': '伏击客'},
'维什戴尔':{'en': "Wiš'adel", 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '投掷手'},
'维娜·维多利亚':{'en': 'Vina Victoria', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '术战者'},
'维荻':{'en': 'Verdant', 'star': '3', 'tag': ['特种干员', '近战位', '生存', '快速复活'], 'subprofession': '傀儡师'},
'缄默德克萨斯':{'en': 'Texas the Omertosa', 'star': '5', 'tag': ['特种干员', '近战位', '快速复活', '输出'], 'subprofession': '处决者'},
'缠丸':{'en': 'Matoimaru', 'star': '3', 'tag': ['近卫干员', '近战位', '生存', '输出'], 'subprofession': '无畏者'},
'缪尔赛思':{'en': 'Muelsyse', 'star': '5', 'tag': ['先锋干员', '远程位', '费用回复', '控场'], 'subprofession': '战术家'},
'罗宾':{'en': 'Robin', 'star': '4', 'tag': ['特种干员', '远程位', '召唤', '位移'], 'subprofession': '陷阱师'},
'罗小黑':{'en': 'Luo Xiaohei', 'star': '3', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '领主'},
'罗比菈塔':{'en': 'Roberta', 'star': '3', 'tag': ['辅助干员', '近战位', '防护', '支援'], 'subprofession': '工匠'},
'羽毛笔':{'en': 'La Pluma', 'star': '4', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '收割者'},
'翎羽':{'en': 'Plume', 'star': '2', 'tag': ['先锋干员', '近战位', '输出', '费用回复'], 'subprofession': '冲锋手'},
'耀骑士临光':{'en': 'Nearl the Radiant Knight', 'star': '5', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '无畏者'},
'老鲤':{'en': 'Lee', 'star': '5', 'tag': ['特种干员', '近战位', '快速复活', '生存', '输出'], 'subprofession': '行商'},
'耶拉':{'en': 'Kjera', 'star': '4', 'tag': ['术师干员', '远程位', '输出', '控场'], 'subprofession': '驭械术师'},
'能天使':{'en': 'Exusiai', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'至简':{'en': 'Minimalist', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '驭械术师'},
'艾丝黛尔':{'en': 'Estelle', 'star': '3', 'tag': ['近卫干员', '近战位', '群攻', '生存'], 'subprofession': '强攻手'},
'艾丽妮':{'en': 'Irene', 'star': '5', 'tag': ['近卫干员', '近战位', '爆发', '输出', '控场'], 'subprofession': '剑豪'},
'艾拉':{'en': 'Ela', 'star': '5', 'tag': ['特种干员', '远程位', '召唤', '控场', '输出'], 'subprofession': '陷阱师'},
'艾雅法拉':{'en': 'Eyjafjalla', 'star': '5', 'tag': ['术师干员', '远程位', '输出', '削弱'], 'subprofession': '中坚术师'},
'芙兰卡':{'en': 'Franka', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '无畏者'},
'芙蓉':{'en': 'Hibiscus', 'star': '2', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '医师'},
'芬':{'en': 'Fang', 'star': '2', 'tag': ['先锋干员', '近战位', '费用回复'], 'subprofession': '尖兵'},
'芳汀':{'en': 'Arene', 'star': '3', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '领主'},
'苇草':{'en': 'Reed', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '冲锋手'},
'苍苔':{'en': 'Bryophyta', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '支援'], 'subprofession': '教官'},
'苏苏洛':{'en': 'Sussurro', 'star': '3', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '医师'},
'苦艾':{'en': 'Absinthe', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '中坚术师'},
'荒芜拉普兰德':{'en': 'Lappland the Decadenza', 'star': '5', 'tag': ['术师干员', '远程位', '输出', '削弱'], 'subprofession': '驭械术师'},
'莎草':{'en': 'Papyrus', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '链愈师'},
'莫斯提马':{'en': 'Mostima', 'star': '5', 'tag': ['术师干员', '远程位', '群攻', '支援', '控场'], 'subprofession': '扩散术师'},
'莱伊':{'en': 'Ray', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '猎手'},
'莱恩哈特':{'en': 'Leonhardt', 'star': '4', 'tag': ['术师干员', '远程位', '群攻', '爆发'], 'subprofession': '扩散术师'},
'莱欧斯':{'en': 'Laios', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '控场'], 'subprofession': '无畏者'},
'菲亚梅塔':{'en': 'Fiammetta', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '炮手'},
'菲莱':{'en': 'Philae', 'star': '4', 'tag': ['重装干员', '近战位', '元素', '防护'], 'subprofession': '本源铁卫'},
'蓝毒':{'en': 'Blue Poison', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'薄绿':{'en': 'Mint', 'star': '4', 'tag': ['术师干员', '远程位', '群攻', '控场'], 'subprofession': '阵法术师'},
'薇薇安娜':{'en': 'Viviana', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '术战者'},
'蚀清':{'en': 'Corroserum', 'star': '4', 'tag': ['术师干员', '远程位', '群攻', '削弱'], 'subprofession': '轰击术师'},
'蛇屠箱':{'en': 'Cuora', 'star': '3', 'tag': ['重装干员', '近战位', '防护'], 'subprofession': '铁卫'},
'蜜莓':{'en': 'Honeyberry', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '行医'},
'蜜蜡':{'en': 'Beeswax', 'star': '4', 'tag': ['术师干员', '远程位', '群攻', '防护'], 'subprofession': '阵法术师'},
'衡沙':{'en': 'Sand Reckoner', 'star': '4', 'tag': ['辅助干员', '远程位', '召唤', '减速'], 'subprofession': '召唤师'},
'裁度':{'en': 'Figurino', 'star': '4', 'tag': ['特种干员', '近战位', '快速复活', '控场'], 'subprofession': '行商'},
'褐果':{'en': 'Chestnut', 'star': '3', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '行医'},
'见行者':{'en': 'Enforcer', 'star': '4', 'tag': ['特种干员', '近战位', '位移', '控场'], 'subprofession': '推击手'},
'角峰':{'en': 'Matterhorn', 'star': '3', 'tag': ['重装干员', '近战位', '防护'], 'subprofession': '铁卫'},
'讯使':{'en': 'Courier', 'star': '3', 'tag': ['先锋干员', '近战位', '费用回复', '防护'], 'subprofession': '尖兵'},
'诗怀雅':{'en': 'Swire', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '支援'], 'subprofession': '教官'},
'调香师':{'en': 'Perfumer', 'star': '3', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '群愈师'},
'谜图':{'en': 'Puzzle', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '快速复活'], 'subprofession': '情报官'},
'豆苗':{'en': 'Beanstalk', 'star': '3', 'tag': ['先锋干员', '远程位', '费用回复', '召唤'], 'subprofession': '战术家'},
'贝娜':{'en': 'Bena', 'star': '4', 'tag': ['特种干员', '近战位', '输出', '快速复活'], 'subprofession': '傀儡师'},
'贾维':{'en': 'Chiave', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '尖兵'},
'赤冬':{'en': 'Akafuyu', 'star': '4', 'tag': ['近卫干员', '近战位', '生存', '输出'], 'subprofession': '武者'},
'赫德雷':{'en': 'Hoederer', 'star': '5', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '重剑手'},
'赫拉格':{'en': 'Hellagur', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '武者'},
'赫默':{'en': 'Silence', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '医师'},
'跃跃':{'en': 'Caper', 'star': '3', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '回环射手'},
'车尔尼':{'en': 'Czerny', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '输出'], 'subprofession': '驭法铁卫'},
'达格达':{'en': 'Dagda', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '生存'], 'subprofession': '斗士'},
'远山':{'en': 'Gitano', 'star': '3', 'tag': ['术师干员', '远程位', '群攻'], 'subprofession': '扩散术师'},
'远牙':{'en': 'Fartooth', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '神射手'},
'迷迭香':{'en': 'Rosmontis', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '投掷手'},
'送葬人':{'en': 'Executor', 'star': '4', 'tag': ['狙击干员', '远程位', '群攻'], 'subprofession': '散射手'},
'逻各斯':{'en': 'Logos', 'star': '5', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '中坚术师'},
'酸糖':{'en': 'Aciddrop', 'star': '3', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '重射手'},
'重岳':{'en': 'Chongyue', 'star': '5', 'tag': ['近卫干员', '近战位', '爆发'], 'subprofession': '斗士'},
'野鬃':{'en': 'Wild Mane', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '冲锋手'},
'铃兰':{'en': 'Suzuran', 'star': '5', 'tag': ['辅助干员', '远程位', '减速', '支援', '输出'], 'subprofession': '凝滞师'},
'铅踝':{'en': 'Totter', 'star': '3', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '攻城手'},
'铎铃':{'en': 'Wind Chimes', 'star': '4', 'tag': ['近卫干员', '近战位', '输出'], 'subprofession': '重剑手'},
'银灰':{'en': 'SilverAsh', 'star': '5', 'tag': ['近卫干员', '近战位', '输出', '支援'], 'subprofession': '领主'},
'铸铁':{'en': 'Sideroca', 'star': '4', 'tag': ['近卫干员', '近战位', '生存', '输出'], 'subprofession': '术战者'},
'锏':{'en': 'Degenbrecher', 'star': '5', 'tag': ['近卫干员', '近战位', '爆发', '输出', '削弱'], 'subprofession': '剑豪'},
'锡人':{'en': 'Tin Man', 'star': '4', 'tag': ['特种干员', '远程位', '削弱', '支援'], 'subprofession': '炼金师'},
'锡兰':{'en': 'Ceylon', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗'], 'subprofession': '疗养师'},
'闪击':{'en': 'Blitz', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '输出'], 'subprofession': '哨戒铁卫'},
'闪灵':{'en': 'Shining', 'star': '5', 'tag': ['医疗干员', '远程位', '治疗', '支援'], 'subprofession': '医师'},
'阿':{'en': 'Aak', 'star': '5', 'tag': ['特种干员', '远程位', '支援', '输出'], 'subprofession': '怪杰'},
'阿斯卡纶':{'en': 'Ascalon', 'star': '5', 'tag': ['特种干员', '近战位', '减速', '输出'], 'subprofession': '伏击客'},
'阿消':{'en': 'Shaw', 'star': '3', 'tag': ['特种干员', '近战位', '位移'], 'subprofession': '推击手'},
'阿米娅':{'en': 'Amiya', 'star': '4', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '中坚术师'},
'阿米娅(医疗)':{'en': 'Amiya', 'star': '4', 'tag': ['医疗干员', '远程位', '治疗', '输出'], 'subprofession': '咒愈师'},
'阿米娅(近卫)':{'en': 'Amiya', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '支援'], 'subprofession': '术战者'},
'阿罗玛':{'en': 'Aroma', 'star': '4', 'tag': ['术师干员', '远程位', '群攻', '控场'], 'subprofession': '轰击术师'},
'陈':{'en': "Ch'en", 'star': '5', 'tag': ['近卫干员', '近战位', '爆发', '输出'], 'subprofession': '剑豪'},
'陨星':{'en': 'Meteorite', 'star': '4', 'tag': ['狙击干员', '远程位', '群攻', '削弱'], 'subprofession': '炮手'},
'隐现':{'en': 'Insider', 'star': '4', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '速射手'},
'雪绒':{'en': 'Qanipalaat', 'star': '4', 'tag': ['术师干员', '远程位', '输出', '控场'], 'subprofession': '中坚术师'},
'雪雉':{'en': 'Snowsant', 'star': '4', 'tag': ['特种干员', '近战位', '位移', '减速'], 'subprofession': '钩索师'},
'雷蛇':{'en': 'Liskarm', 'star': '4', 'tag': ['重装干员', '近战位', '防护', '输出'], 'subprofession': '哨戒铁卫'},
'霍尔海雅':{'en': "Ho'olheyak", 'star': '5', 'tag': ['术师干员', '远程位', '输出', '控场'], 'subprofession': '中坚术师'},
'霜华':{'en': 'Frost', 'star': '4', 'tag': ['特种干员', '远程位', '召唤', '控场'], 'subprofession': '陷阱师'},
'霜叶':{'en': 'Frostleaf', 'star': '3', 'tag': ['近卫干员', '近战位', '减速', '输出'], 'subprofession': '领主'},
'露托':{'en': 'Lutonada', 'star': '3', 'tag': ['重装干员', '近战位', '生存', '防护'], 'subprofession': '不屈者'},
'青枳':{'en': 'Poncirus', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '防护'], 'subprofession': '尖兵'},
'鞭刃':{'en': 'Whislash', 'star': '4', 'tag': ['近卫干员', '近战位', '输出', '支援'], 'subprofession': '教官'},
'风丸':{'en': 'Kazemaru', 'star': '4', 'tag': ['特种干员', '近战位', '输出', '快速复活'], 'subprofession': '傀儡师'},
'风笛':{'en': 'Bagpipe', 'star': '5', 'tag': ['先锋干员', '近战位', '费用回复', '输出'], 'subprofession': '冲锋手'},
'食铁兽':{'en': 'FEater', 'star': '4', 'tag': ['特种干员', '近战位', '位移', '减速'], 'subprofession': '推击手'},
'香草':{'en': 'Vanilla', 'star': '2', 'tag': ['先锋干员', '近战位', '费用回复'], 'subprofession': '尖兵'},
'魔王':{'en': 'Civilight Eterna', 'star': '5', 'tag': ['辅助干员', '远程位', '支援', '生存', '输出'], 'subprofession': '吟游者'},
'鸿雪':{'en': 'Позёмка', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '重射手'},
'麒麟R夜刀':{'en': 'Kirin R Yato', 'star': '5', 'tag': ['特种干员', '近战位', '快速复活', '爆发'], 'subprofession': '处决者'},
'麦哲伦':{'en': 'Magallan', 'star': '5', 'tag': ['辅助干员', '远程位', '支援', '减速', '输出'], 'subprofession': '召唤师'},
'黍':{'en': 'Shu', 'star': '5', 'tag': ['重装干员', '近战位', '防护', '治疗', '支援'], 'subprofession': '守护者'},
'黑':{'en': 'Schwarz', 'star': '5', 'tag': ['狙击干员', '远程位', '输出'], 'subprofession': '重射手'},
'黑角':{'en': 'Noir Corne', 'star': '1', 'tag': ['重装干员', '近战位', '新手'], 'subprofession': '铁卫'},
'黑键':{'en': 'Ebenholz', 'star': '5', 'tag': ['术师干员', '远程位', '输出'], 'subprofession': '秘术师'},
'齐尔查克':{'en': 'Chilchuck', 'star': '4', 'tag': ['先锋干员', '近战位', '费用回复', '快速复活'], 'subprofession': '情报官'},
'龙舌兰':{'en': 'Tequila', 'star': '4', 'tag': ['近卫干员', '近战位', '爆发'], 'subprofession': '解放者'},
}

data = Data()